const datasetMain = [
  {
    id: 1,
    image: './img/bolo-1.jpeg',
    title: 'Bolos Customizados',
    description: 'Peça o seu bolo totalmente customizado',
    image1: './img/catalogo-img/cat1-custom2.jpeg',
    image2: './img/catalogo-img/cat1-custom3.jpeg',
    price: 20.00,
  },
  {
    id: 2,
    image: './img/bolo-2.jpeg',
    title: 'Tortas',
    description: 'Tortas disponíveis para entrega em menos de 3 dias',
    image1: './img/catalogo-img/cat2-torta1.jpeg',
    image2: './img/catalogo-img/cat2-torta2.jpeg',
    price: 21.00,
  },
  {
    id: 3,
    image: './img/bolo-3.jpeg',
    title: 'Docinhos',
    description: 'Doces disponíveis para entrega em menos de 3 dias',
    image1: './img/catalogo-img/cat3-docinho1.jpeg',
    image2: './img/catalogo-img/cat3-docinho2.jpeg',
    price: 22.00,
  },
  {
    id: 4,
    image: './img/bolo-4.jpeg',
    title: 'Cupcakes',
    description: 'Peça o seu Cupcake totalmente customizada',
    image1: './img/catalogo-img/cat4-cupcake1.jpeg',
    image2: './img/catalogo-img/cat4-cupcake2.jpeg',
    price: 23.00,
  },
  {
    id: 5,
    image: './img/bolo-5.jpeg',
    title: 'Pudins',
    description: 'Pudins disponíveis para entrega em menos de 3 dias',
    image1: './img/catalogo-img/cat5-pudim1.jpeg',
    image2: './img/catalogo-img/cat5-pudim2.jpeg',
    price: 24.00,
  },
  {
    id: 6,
    image: './img/bolo-6.jpeg',
    title: 'Bolos de Aniversário',
    description: 'Peça o seu bolo de aniversário totalmente customizado',
    image1: './img/catalogo-img/cat6-aniversario.jpeg',
    image2: './img/catalogo-img/cat6-aniversario2.jpeg',
    price: 25.00,
  },
];

export default datasetMain;